import './globals.css'
import Hero from "@/components/Hero";
import Menu from '@/components/Menu';
import { Nav } from "@/components/Nav";
import { BookListProvider } from '@/context/BookListContext';
import { ToastProvider } from '@/context/ToastContext';
import { AuthContextProvider } from '@/context/authContext';
import { BodyContainerProvider } from '@/context/bodyContainerContext';
import { BooksProvider } from '@/context/booksContext';
import { VisitorProvider } from '@/context/visitorContext';
import { WindowDimensionsProvider } from '@/context/windowDimensionsContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body >
      <WindowDimensionsProvider>
      <ToastProvider>
      <BodyContainerProvider>
        <VisitorProvider>
        <AuthContextProvider>
        <BookListProvider>
        <BooksProvider>
        {children}
        
        </BooksProvider>
        </BookListProvider>
        </AuthContextProvider>
        </VisitorProvider>
        </BodyContainerProvider>
        </ToastProvider>
        </WindowDimensionsProvider>
      </body>
    </html>
  )
}

// export async function getServerSideProps({ req }) {
//   const token = req.cookies.token || ""; // Retrieve the token from cookies
//   return {
//     props: {
//       token,
//     },
//   };
// }
