import './globals.css'
import Hero from "@/components/Hero";
import Menu from '@/components/Menu';
import { Nav } from "@/components/Nav";
import { AuthContextProvider } from '@/context/authContext';
import { BooksProvider } from '@/context/booksContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body >
        
        <AuthContextProvider>
        <BooksProvider>
        {children}
        </BooksProvider>
        </AuthContextProvider>
        
      </body>
    </html>
  )
}

// export async function getServerSideProps({ req }) {
//   const token = req.cookies.token || ""; // Retrieve the token from cookies
//   return {
//     props: {
//       token,
//     },
//   };
// }
